RAVIO/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "RAVIO Video Admin Panel"
admin.site.site_title = "RAVIO Video Admin Portal"
admin.site.index_title = "Welcome to RAVIO!"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('videoapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videoapp/models.py
from django.db import models
from django.contrib.auth.models import User
from numpy import negative


class VideoPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    desc = models.TextField()
    video_file = models.FileField(upload_to='videos/')
    thumbnail = models.ImageField(upload_to='videos/thumbnail/', default='none')
    category = models.CharField(max_length=50, default='none')
    pub_date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='likes')
    video_views = models.ManyToManyField(User, related_name='video_views')
    positive_comment = models.IntegerField(default=0)
    negative_comment = models.IntegerField(default=0)

    def __str__(self):
        return self.title




class UserData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField()
    profile_pic = models.ImageField(upload_to='pic/', default='pic/default.jpg')
    subscribers = models.ManyToManyField(User, related_name='subscribers')




class Comment(models.Model):
    post = models.ForeignKey(VideoPost, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300)
    sentiment = models.IntegerField(default=1)

    def __str__(self):
        return self.user.username

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!--Animation-->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>RAVIO</title>
  </head>
  <body>
    {% load static %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">RAVIO</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'home' %}"
                >Home</a
              >
            </li>
            <form class="d-flex" action="{% url 'search' %}" method="get">
              <input
                class="form-control me-2 mx-4"
                name="search_query"
                style="width: 700px"
                type="search"
                placeholder="Search User"
                aria-label="Search"
              />
              <button
                class="btn btn-outline-success"
                type="submit"
                style="color: white; border-color: white"
              >
                Search
              </button>
            </form>
          </ul>

          {% if not user.is_authenticated %}
          <button
            class="btn btn-outline-success mx-3"
            data-bs-toggle="modal"
            data-bs-target="#loginModal"
          >
            Login
          </button>
          <button
            class="btn btn-outline-warning"
            data-bs-toggle="modal"
            data-bs-target="#signupModal"
          >
            Signup
          </button>
          {% else %}
          <div class="btn-group mx-4">
            <button
              type="button"
              class="btn btn-secondary dropdown-toggle"
              data-bs-toggle="dropdown"
              data-bs-display="static"
              aria-expanded="false"
            >
              @{{request.user}}
            </button>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start">
              <a
                href="{% url 'profile' request.user.username %}"
                style="text-decoration: none"
                ><li>
                  <button class="dropdown-item" type="button">
                    Your Channel
                  </button>
                </li></a
              >
              <a
                href="{% url 'dashboard' request.user.username %}"
                style="text-decoration: none"
                ><li>
                  <button class="dropdown-item" type="button">Dashboard</button>
                </li></a
              >
              <a href="{% url 'upload' %}" style="text-decoration: none"
                ><li>
                  <button class="dropdown-item" type="button">
                    Upload Video
                  </button>
                </li></a
              >
              <a href="{% url 'hashtag' %}" style="text-decoration: none"
                ><li>
                  <button class="dropdown-item" type="button">
                    Top Hashtags
                  </button>
                </li></a
              >
              <li><hr class="dropdown-divider" /></li>
              <a href="{% url 'logout' %}" style="text-decoration: none"
                ><li class="text-danger">
                  <button class="dropdown-item text-danger" type="button">
                    Logout
                  </button>
                </li></a
              >
            </ul>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>

    {% if messages %} {% for message in messages %}
    <div
      class="alert alert-{{message.tags}} alert-dismissible fade show"
      role="alert"
    >
      <strong>{{message}}</strong>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endfor %} {% endif %} {% block body%}{% endblock %}

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/edit.html
{% extends 'base.html' %} {% load static %} {% block body%}

<div class="container border py-4 my-4 w-75">
  <form action="{% url 'upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-3">
      <label for="filename" class="form-label">Select Video File</label>
      <input
        type="file"
        name="fileName"
        class="form-control"
        id="filename"
        accept="video/*"
        required
      />
    </div>

    <button type="submit" class="btn btn-primary">Upload</button>
  </form>
</div>

{% endblock %}

templates/hashtag.html
{% extends 'base.html' %} {% load static %} {% block body%}
<body>
  <div style="margin-left: 5%; margin-top: 5%">
    <h1>Trending Hashtags</h1>
    <h2>
      <ol>
        {% for hashtag in hashtags %}
        <li>{{hashtag}}</li>
        {% endfor %}
      </ol>
    </h2>
  </div>
</body>

{% endblock %}

templates/home.html
{% extends 'base.html' %} {% load static %} {% block body %}

<div class="container">
  <div class="row my-4">
    {% for video in all_videos %}
    <div class="col-3">
      <a href="{% url 'watch_video' video.id %}" style="text-decoration: none">
        <img src="{% static video.thumbnail.url %}" class="w-100" />
      </a>
      <a href="{% url 'watch_video' video.id %}" style="text-decoration: none">
        <h6>{{video.title}}</h6>
      </a>
      <span class="text-muted"
        >{{video.video_views.all.count}} views • {{video.pub_date}}</span
      >
    </div>
    {% endfor %}

    <hr />
  </div>

  {% endblock %}
</div>

templates/profile.html
{% extends 'base.html' %} {% load static %} {% block body %}
<!--Profile Image and Name-->
<div class="container my-4">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <img
          src="{% static user_data.profile_pic.url %}"
          class="img-thumbnail"
          style="width: 150px; height: 200px"
        />
      </div>
      <div class="col">
        <h2 style="margin-top: 80px">
          {{session_obj.first_name}} {{session_obj.last_name}}
        </h2>
        <span class="text-muted"
          ><span class="text-muted" id="count"
            >{{user_data.subscribers.count}}</span
          >
          Subscribers</span
        >
        {% if session_obj != request.user %} {% if subscribed %}
        <a id="sub_btn" class="btn btn-outline-danger mx-3">Unsubscribe</a>
        {% else %}
        <a id="sub_btn" class="btn btn-outline-danger mx-3">Subscribe</a>
        {% endif %} {% endif %}
      </div>
    </div>
  </div>
</div>
<!--End of Profile Image and Name-->

<hr />
<div class="container">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a
        class="nav-link active"
        id="home-tab"
        data-bs-toggle="tab"
        href="#home"
        role="tab"
        aria-controls="home"
        aria-selected="true"
        >Home</a
      >
    </li>
    <li class="nav-item" role="presentation">
      <a
        class="nav-link"
        id="profile-tab"
        data-bs-toggle="tab"
        href="#profile"
        role="tab"
        aria-controls="profile"
        aria-selected="false"
        >Videos</a
      >
    </li>
    <li class="nav-item" role="presentation">
      <a
        class="nav-link"
        id="contact-tab"
        data-bs-toggle="tab"
        href="#contact"
        role="tab"
        aria-controls="contact"
        aria-selected="false"
        >About</a
      >
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div
      class="tab-pane fade show active"
      id="home"
      role="tabpanel"
      aria-labelledby="home-tab"
    >
      <h3 class="my-3">Category wise videos</h3>
      <hr />

      {% if sci %}
      <div class="row">
        <h4 class="text-primary">Science & Technology</h4>

        {% for v in sci %}
        <div class="col-3">
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><img
              src="{% static v.thumbnail.url %}"
              style="width: 100%"
              class="img-thumbnail"
          /></a>
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><h6>{{v.title}}</h6></a
          >
          <span class="text-muted"
            >{{v.video_views.all.count}} views • {{v.pub_date}}</span
          >
        </div>
        {% endfor %}
      </div>
      <hr />
      {% endif %} {% if blogs %}
      <div class="row">
        <h4 class="text-primary">Blogs</h4>

        {% for v in blogs %}
        <div class="col-3">
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><img
              src="{% static v.thumbnail.url %}"
              style="width: 100%"
              class="img-thumbnail"
          /></a>
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><h6>{{v.title}}</h6></a
          >
          <span class="text-muted"
            >{{v.video_views.all.count}} views • {{v.pub_date}}</span
          >
        </div>
        {% endfor %}
      </div>
      <hr />
      {% endif %} {% if food %}
      <div class="row">
        <h4 class="text-primary">Food</h4>

        {% for v in food%}
        <div class="col-3">
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><img src="{% static v.thumbnail.url %}" class="img-thumbnail w-75"
          /></a>
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><h6>{{v.title}}</h6></a
          >
          <span class="text-muted"
            >{{v.video_views.all.count}} views • {{v.pub_date}}</span
          >
        </div>
        {% endfor %}
      </div>
      <hr />
      {% endif %} {% if edu %}
      <div class="row">
        <h4 class="text-primary">Education</h4>

        {% for v in edu%}
        <div class="col-3">
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><img src="{% static v.thumbnail.url %}" class="img-thumbnail w-75"
          /></a>
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><h6>{{v.title}}</h6></a
          >
          <span class="text-muted"
            >{{v.video_views.all.count}} views • {{v.pub_date}}</span
          >
        </div>
        {% endfor %}
      </div>
      <hr />
      {% endif %} {% if fashion %}
      <div class="row">
        <h4 class="text-primary">Fashion</h4>

        {% for v in fashion %}
        <div class="col-3">
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><img src="{% static v.thumbnail.url %}" class="img-thumbnail w-75"
          /></a>
          <a href="{% url 'watch_video' v.id %}" style="text-decoration: none"
            ><h4>{{v.title}}</h4></a
          >
          <span class="text-muted"
            >{{v.video_views.all.count}} views • {{v.pub_date}}</span
          >
        </div>
        {% endfor %}
      </div>
      <hr />
      {% endif %}
    </div>
    <div
      class="tab-pane fade"
      id="profile"
      role="tabpanel"
      aria-labelledby="profile-tab"
    >
      <div class="container">
        <h3 class="my-3">Uploads</h3>
        <div class="row my-3">
          {% if videos %} {% for video in videos %}
          <div class="col-3">
            <a
              href="{% url 'watch_video' video.id %}"
              style="text-decoration: none"
              ><img
                src="{% static video.thumbnail.url %}"
                style="width: 100%"
                class="img-thumbnail"
            /></a>
            <a
              href="{% url 'watch_video' video.id %}"
              style="text-decoration: none"
              ><h6>{{video.title}}</h6></a
            >
            <span class="text-muted"
              >{{video.video_views.all.count}} views • {{video.pub_date}}</span
            >
          </div>
          {% endfor %} {% else %}
          <h3>No Videos.</h3>
          {% endif %}
        </div>
        <hr />
      </div>
    </div>

    <div
      class="tab-pane fade"
      id="contact"
      role="tabpanel"
      aria-labelledby="contact-tab"
    >
      <div class="container my-4">
        <p><b>Description</b></p>
        <pre
          style="font-family: tahoma; letter-spacing: 1px"
        ><p>{{user_data.about}}</p></pre>
        <hr />

        <p><b>Details</b></p>
        <p>Email:</p>
        <a href="mailto:{{session_obj.email}}"><p>{{session_obj.email}}</p></a>
        <hr />

        <p><b>Links: </b></p>
        <p>Instagram</p>
        <p>Github</p>
        <p>Twitter</p>
        <p>Facebook</p>
        <hr />
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var btn = $("#sub_btn");
  var count = $("#count");
  // btn.text('Subscribe');
  btn.on("click", function (event) {
    event.preventDefault();

    $.ajax({
      type: "GET",
      url: '{% url "add_subscriber" session_obj.username %}',
      dataType: "json",
      success: function (data) {
        if (data.is_subscribed) {
          // alert(data.is_subscribed);
          btn.text("Subscribe");
          count.text(data.viewer_obj);
          console.log(data.viewer_obj);
        } else {
          // alert(data.is_subscribed);
          btn.text("Unsubscribe");
          count.text(data.viewer_obj);
          console.log(data.viewer_obj);
        }
      },
    });
  });
</script>
{% endblock %}

templates/search_page.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container my-4">
    <h3>Search Results: </h3>
    {% if user_obj %}
    <div class="row">
    {% for user in user_obj %}
    <div class="col-4">
    <div class="card my-3" style="width: 18rem;">
        <img src="{% static user.userdata.profile_pic.url %}" class="img-thumbnail card-img-top" style="height: 250px;" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{user.username}}</h5>
            <p class="card-text">{{user.userdata.about|truncatewords:6}}</p>
            <a href="{% url 'profile' user.username %}" class="btn btn-primary">View Profile</a>
        </div>
    </div>
    </div>
    {% endfor %}
    </div>
    {% else %}
    <div class="container">
        <h5>No Results Found.</h5>
    </div>
    {% endif %}
</div>  
{% endblock %}

templates/upload_video.html
{% extends 'base.html' %} {% load static %} {% block body%}

<div class="container border py-4 my-4 w-75">
  <form action="{% url 'upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <label for="title" class="form-label">Title</label>
      <input
        type="text"
        name="title"
        class="form-control"
        id="title"
        required
      />
    </div>

    <div class="mb-3">
      <label for="desc" class="form-label">Description</label>
      <textarea
        class="form-control"
        name="desc"
        id="desc"
        style="height: 200px"
        required
      ></textarea>
    </div>

    <div class="mb-3">
      <label for="filename" class="form-label">Select Video File</label>
      <input
        type="file"
        name="fileName"
        class="form-control"
        id="filename"
        accept="video/*"
        required
      />
    </div>

    <div class="mb-3">
      <label for="thumb" class="form-label">Select Thumbnail</label>
      <input
        type="file"
        name="thumbnail_img"
        class="form-control"
        id="thumb"
        accept="image/*"
        required
      />
    </div>

    <div class="mb-3">
      <label for="title" class="form-label">Select Category</label>
      <select class="form-control" name="category">
        <option>Science & Technology</option>
        <option>Fashion</option>
        <option>Food</option>
        <option>Education</option>
        <option>Blogs</option>
      </select>
    </div>

    <button type="submit" class="btn btn-primary">Upload</button>
  </form>
</div>

{% endblock %}

templates/watch_video.html
{% extends 'base.html' %} {% load static %} {% block body %}
<div class="row">
  <div class="col-8">
    <div
      class="container py-2 my-4 w-auto"
      style="position: absolute; left: 100px"
    >
      <div
        id="carouselExampleSlidesOnly"
        class="carousel slide"
        data-bs-ride="carousel"
      >
        <div class="carousel-inner">
          <div class="carousel-item active">
            <video width="100%" controls>
              <source
                src="{% static video.video_file.url %}"
                type="video/mp4"
              />
            </video>
          </div>
        </div>
      </div>

      <div class="card w-auto">
        <div class="card-body">
          <h5 class="card-title">{{video.title}}</h5>
          <span class="badge rounded-pill bg-info text-dark"
            >{{video.category}}</span
          >
          <div class="row">
            <div class="col-8">
              <span class="text-muted"
                >{{video.video_views.all.count}} views •
                {{video.pub_date}}</span
              >
            </div>
            <div class="col">
              {% if is_liked %}

              <a id="like_btn" class="btn btn-outline-danger mx-3"
                ><span id="count_likes">{{video.likes.all.count}}</span
                >&nbsp&nbsp<span id="like_icon"
                  ><svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    fill="currentColor"
                    class="bi bi-heart-fill"
                    viewBox="0 0 16 16"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"
                    />
                  </svg> </span
              ></a>
              {% else %}

              <a id="like_btn" class="btn btn-outline-danger mx-3"
                ><span id="count_likes">{{video.likes.all.count}}</span
                >&nbsp&nbsp<span id="like_icon"
                  ><svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    fill="currentColor"
                    class="bi bi-heart"
                    viewBox="0 0 16 16"
                  >
                    <path
                      d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"
                    />
                  </svg> </span
              ></a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>

      <div class="card my-2">
        <div class="card-header">
          <h6><b>DESCRIPTION</b></h6>
        </div>

        <div class="card-body">
          <pre><p>{{video.desc}}</p></pre>
        </div>
      </div>
      <div class="card my-2">
        <div class="card-header">
          <h6><b>UP NEXT</b></h6>
        </div>
        <div class="list-group my-2">
          {% for v in video.user.videopost_set.all %}
          <a
            href="{% url 'watch_video' v.id %}"
            class="list-group-item list-group-item-action"
            aria-current="true"
          >
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">{{v.title}}</h5>
              <small>{{v.pub_date}}</small>
            </div>
            <p class="mb-1">{{v.desc}}</p>
          </a>
          {% endfor %}
        </div>
      </div>
      <h2 class="accordion-header" id="flush-headingTwo">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#flush-collapseTwo"
          aria-expanded="false"
          aria-controls="flush-collapseTwo"
        >
          <b>COMMENTS (<span id="count_comment">{{comments.count}}</span>) | Postive : {{video.positive_comment}} | Negative : {{video.negative_comment}}</b>
        </button>
      </h2>
      <div
        id="flush-collapseTwo"
        class="accordion-collapse collapse"
        aria-labelledby="flush-headingTwo"
        data-bs-parent="#accordionFlushExample"
      >
        <div class="container my-2">
            <ul class="list-group" id="menu">
                {% for comment in comments %}
                <b>{{comment}}</b>
                {% if comment.sentiment == 1 %}
                <li class="list-group-item" style="color: green">
                  {{comment.comment}}
                </li>
                {% else %}
                <li class="list-group-item" style="color: red">
                  {{comment.comment}}
                </li>
                {% endif %} {% endfor %}
              </ul>
        </div>
        <div class="accordion-body">
          <form id="my_form">
            <textarea
              class="form-control"
              name="comment"
              id="comment"
              placeholder="Write your comment..."
            ></textarea>
            <input
              class="btn btn-outline-success my-3"
              id="send_btn"
              type="submit"
              value="Comment"
            />
          </form>
        </div>
      </div>
    </div>
  </div>
  </div>
</div>

<script type="text/javascript">
  var send_btn = $("#send_btn");
  send_btn.on("click", function (event) {
    event.preventDefault();
    var comment = $("#comment").val();
    var ul_menu = $("#menu");
    var count_comment = $("#count_comment");

    $.ajax({
      type: "GET",
      url: '{% url "add_comment" %}',
      data: { comment_text: comment, video_id: "{{video.id}}" },
      dataType: "json",
      success: function (data) {
        if (data.comment) {
          var comment_res = data.comment;
          var li_html =
            "<b>{{request.user}}</b><li class='list-group-item'>" +
            comment_res +
            "</li>";

          ul_menu.prepend(li_html);
          count_comment.text(data.count_comments);
          $("#my_form").trigger("reset");
        }
      },
    });
  });
</script>

<script type="text/javascript">
  var like_btn = $("#like_btn");
  like_btn.on("click", function (event) {
    event.preventDefault();
    var count_likes = $("#count_likes");
    var like_icon = $("#like_icon");

    $.ajax({
      url: '{% url "add_like" video.id %}',
      data: {},
      dataType: "json",
      success: function (data) {
        if (data.is_liked) {
          like_icon.html(
            '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16"><path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></svg>'
          );
          count_likes.text(data.likes_count);
        } else {
          like_icon.html(
            '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>'
          );
          count_likes.text(data.likes_count);
        }
      },
    });
  });
</script>

{% endblock %}